;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
		))

(setq mc/cmds-to-run-once
      '(
		eshell
		helm-M-x
		mc/mark-next-lines
		org-force-self-insert
		org-self-insert-command
		point-undo
		save-buffers-kill-terminal
		undo-tree-visualize
		yas-expand
		))
