;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
		org-beginning-of-line
		org-force-self-insert
		org-return-indent
		org-self-insert-command
		))

(setq mc/cmds-to-run-once
      '(
		describe-key-briefly
		eshell
		helm-M-x
		helm-for-files
		mc/mark-next-lines
		point-undo
		save-buffers-kill-terminal
		undo-tree-visualize
		yas-expand
		))
